# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7801b9edbdea42624ff30875d2aa5c83"
application_url = "https://styleback-app.onrender.com"
embedded = true
name = "StyleBack"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,write_discounts"



[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/checkouts"
  topics = [ "checkouts/create", "checkouts/update" ]

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://styleback-app.onrender.com/webhooks/customers/redact"
  customer_data_request_url = "https://styleback-app.onrender.com/webhooks/customers/data_request"
  shop_deletion_url = "https://styleback-app.onrender.com/webhooks/shop/redact"

[auth]
redirect_urls = [
  "https://styleback-app.onrender.com/auth/callback",
  "https://styleback-app.onrender.com/auth/shopify/callback",
  "https://styleback-app.onrender.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
